server:
  port: 8081

logging:
  level:
    root: DEBUG

spring:
  application:
    name: search
  data:
    rest:
      base-path: /drugs
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password:
    username:
    url: jdbc:mysql://61.19.242.56:3306/chat
  jpa:
    show-sql: true