server:
  port: 8081

logging:
  level:
    root: DEBUG

spring:
  application:
    name: search
  data:
    rest:
      base-path:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: P@ssw0rd
    username: root
    url: jdbc:mysql://61.19.242.56:3305/chat
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true
