server:
  port: 8081

logging:
  level:
    root: DEBUG

spring:
  application:
    name: search
  data:
    rest:
      base-path:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 
    username:
    url: jdbc:mysql://localhost/chat
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true
